"""add image file info cols

Revision ID: a328dcd7a2f2
Revises: d9c47e89f4f2
Create Date: 2023-09-03 09:56:06.578907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a328dcd7a2f2'
down_revision = 'd9c47e89f4f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('code', sa.String(length=256), nullable=False))
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'size')
    op.drop_column('file', 'code')
    # ### end Alembic commands ###
